(ns anvil.web.params-parse
  "Lightweight extractor for the Jenkinsfile `parameters { … }` block
   (TU4.1).

   The current translator stores `:parameters [{:raw \"<parameters block>\"}]`
   — a stub. Doing a full Groovy AST walk for parameter definitions is
   a larger refactor; for v1 the trigger form needs ENOUGH structure
   to render real inputs, so we regex the raw source for the four
   shapes that cover ~95% of real Jenkinsfiles:

     string(name: 'X', defaultValue: 'Y', description: 'Z')
     booleanParam(name: 'X', defaultValue: true)
     choice(name: 'X', choices: ['a', 'b', 'c'])      ; or choices: 'a\\nb\\nc'
     password(name: 'X', defaultValue: '')
     file(name: 'X', description: 'Z')

   Cases the regex doesn't cover (documented + tested for graceful
   degradation):
     - Multi-line `description` blocks built via Groovy concatenation
     - Parameters generated by helper methods or @Library calls
     - Active Choices plugin (separate IR layer; v2 territory)

   The output shape is a vec of:
     {:kind   :string | :boolean | :choice | :password | :file
      :name   STR
      :default ANY        (string default, true/false, first choice, etc.)
      :description STR
      :choices [STR ...]  (only for :choice)
      :required? BOOL     (always false at v1 — Jenkins parameters are
                          all optional unless explicit `required: true`)}

   Order is preserved: parameters appear in the same order as the
   source so the rendered form matches the Jenkinsfile author's intent.

   Tested in anvil.web.params-parse-test."
  (:require [clojure.string :as str]))

;; ---------------------------------------------------------------------------
;; Locate the parameters { ... } block
;; ---------------------------------------------------------------------------

(defn- locate-block
  "Return the substring inside the outermost `parameters { … }` block,
   or nil if no such block.

   Uses a word-boundary on `parameters` rather than requiring it at
   line start — real Jenkinsfiles sometimes put `agent any; parameters {`
   inline."
  [^String source]
  (when source
    (when-let [m (re-find #"(?m)\bparameters\s*\{" source)]
      (let [open-idx (.indexOf source m)
            scan-start (+ open-idx (.indexOf m "{") 1)]
        ;; Brace-counter from `scan-start`. Crude but Jenkinsfiles in
        ;; the wild don't put unbalanced braces inside strings inside
        ;; this block.
        (loop [i scan-start, depth 1]
          (cond
            (>= i (count source))   nil
            (zero? depth)           (subs source scan-start (dec i))
            :else
            (let [c (.charAt source i)]
              (cond
                (= c \{) (recur (inc i) (inc depth))
                (= c \}) (if (= 1 depth)
                           (subs source scan-start i)
                           (recur (inc i) (dec depth)))
                :else    (recur (inc i) depth)))))))))

;; ---------------------------------------------------------------------------
;; Per-call extractors
;; ---------------------------------------------------------------------------

(defn- unquote-str
  "Strip Groovy single/double quotes around `s`, or return s as-is."
  [^String s]
  (cond
    (nil? s)               nil
    (and (>= (count s) 2)
         (or (and (= \' (first s)) (= \' (last s)))
             (and (= \" (first s)) (= \" (last s)))))
    (subs s 1 (dec (count s)))
    :else s))

(defn- extract-named-arg
  "Find a `key: VALUE` named-arg inside `call-args` and return its
   raw string (with quotes / brackets preserved), or nil.

   Hand-coded scanner because Java regex can't balance brackets:
   values can be bare literals, quoted strings (possibly containing
   commas), bracketed lists, or sub-call expressions."
  [^String call-args ^String k]
  (let [pat (re-pattern (str "(?m)\\b" k "\\s*:\\s*"))
        m (re-matcher pat call-args)]
    (when (.find m)
      (let [start (.end m)
            n (count call-args)]
        (loop [i start
               depth 0
               in-str nil]
          (cond
            (>= i n)
            (str/trim (subs call-args start n))

            in-str
            (let [c (.charAt call-args i)]
              (cond
                (and (= c \\) (< (inc i) n))   (recur (+ i 2) depth in-str)
                (= c in-str)                    (recur (inc i) depth nil)
                :else                           (recur (inc i) depth in-str)))

            :else
            (let [c (.charAt call-args i)]
              (cond
                (or (= c \') (= c \"))         (recur (inc i) depth c)
                (#{\[ \( \{} c)                (recur (inc i) (inc depth) in-str)
                (#{\] \) \}} c)                (if (zero? depth)
                                                  (str/trim (subs call-args start i))
                                                  (recur (inc i) (dec depth) in-str))
                (and (= c \,) (zero? depth))   (str/trim (subs call-args start i))
                :else                           (recur (inc i) depth in-str)))))))))

(defn- parse-bool [^String s]
  (case (some-> s str/trim str/lower-case)
    "true"  true
    "false" false
    nil))

(defn- parse-choices
  "Parse the value of `choices:` — either `[a, b, c]` or `'a\\nb\\nc'`."
  [^String raw]
  (when raw
    (let [t (str/trim raw)]
      (cond
        (str/starts-with? t "[")
        (->> (-> t
                 (subs 1 (max 1 (dec (count t))))
                 (str/split #","))
             (map #(unquote-str (str/trim %)))
             (remove str/blank?)
             vec)

        :else
        (->> (-> (unquote-str t) (or "") (str/split #"\\n|\n"))
             (map str/trim)
             (remove str/blank?)
             vec)))))

(defn- ->param
  "Build a normalized parameter map from one matched call. `kind` is
   :string/:boolean/:choice/:password/:file."
  [kind call-args]
  (let [nm   (unquote-str (extract-named-arg call-args "name"))
        desc (unquote-str (or (extract-named-arg call-args "description") ""))
        base {:kind kind
              :name nm
              :description (or desc "")
              :required? false}]
    (case kind
      :string
      (assoc base :default (unquote-str (extract-named-arg call-args "defaultValue")))

      :password
      (assoc base :default (unquote-str (or (extract-named-arg call-args "defaultValue") "")))

      :boolean
      (assoc base :default (or (parse-bool (extract-named-arg call-args "defaultValue")) false))

      :choice
      (let [choices (or (parse-choices (extract-named-arg call-args "choices")) [])]
        (-> base
            (assoc :choices choices)
            (assoc :default (first choices))))

      :file
      base)))

(def ^:private call-pat
  ;; (string|booleanParam|choice|password|file)( ... )
  ;; Non-greedy match inside parens; assumes args don't contain unbalanced ')'.
  #"(?ms)(string|booleanParam|choice|password|file)\s*\(\s*((?:[^()]|\([^()]*\))*?)\s*\)")

(defn- kind-keyword [^String call-name]
  (case call-name
    "string"       :string
    "booleanParam" :boolean
    "choice"       :choice
    "password"     :password
    "file"         :file))

(defn extract
  "Return a vec of parameter maps parsed from `source`. Empty if the
   source has no `parameters { }` block or all entries failed to
   parse a `name:`."
  [^String source]
  (let [block (locate-block source)]
    (if-not block
      []
      (let [m (re-matcher call-pat block)]
        (loop [acc []]
          (if (.find m)
            (let [kind (kind-keyword (.group m 1))
                  args (.group m 2)
                  p (->param kind args)]
              (recur (if (str/blank? (:name p))
                       acc
                       (conj acc p))))
            acc))))))
